### ISSUE TITLE
Ок)

### ISSUE THREAD

**Issue by mashed-potatoes** [shogo-makishima/SchoolDiary#1]
https://github.com/shogo-makishima/SchoolDiary/blob/8cb6c755930fc9318ebfbcd0b6a0d8e2768587ad/Scripts/Main/NetSchoolShell.py#L102

**Comment by shogo-makishima** [comment]
Спасибо, забыл удалить строку)

**Comment by mashed-potatoes** [comment]
https://stackoverflow.com/a/872700
